name: hourhero
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  velocity_x: ^4.1.0
  flutter_bloc: ^8.1.3
  auto_route: ^7.4.0
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/bg_splash_screen.jpg
    - assets/icon_google.png
